### ISSUE TITLE
"Error: Unable to verify github.com attribute of certificate"

### ISSUE THREAD

**Issue by Blendertesmorts** [AgentRG/swtor_on_mac#39]
Hi everyone, 

I'm on a Macbook Pro late 2015 under OS Monterey 12.7.4 with an Intel chip. Every time I'm running the script to install swtor I get to the same error message at the end of step 3 "Error : Unable to verify github.com attribute of certificate" and ask me to use the command "--no-check-certificate" but even then it shows me the same error message, someone knows how can I fix this ? 

Thanks a lot

**Comment by AgentRG** [comment]
Hello. I have since long sunset the project as it has served its purpose for me. Now, it is open source and unmaintained. This script will probably not not work, but this new guide will work, maybe: https://www.reddit.com/r/swtor/comments/17790ut/playing_swtor_on_apple_silicon_m1_m2/

Regarding your error, most likely you do not have ca-certificates installed. You can probably fix this quickly by running `brew install ca-certificates` if you have Homebrew installed. Since this particular issue is not related to the script, I will close this issue.
